#!/usr/bin/env python3
"""Generate or check docs/CLI.md from Gearu's argparse definitions."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DOCS_PATH = REPO / "docs" / "CLI.md"
sys.path.insert(0, str(REPO / "src"))

from gearu.cli import build_parser


def generated_markdown() -> str:
    parser = build_parser()
    subparsers = next(
        action
        for action in parser._actions
        if isinstance(action, argparse._SubParsersAction)
    )
    sections = [("gearu", parser.format_help())]
    sections.extend(
        (f"gearu {name}", command.format_help())
        for name, command in subparsers.choices.items()
    )

    output = [
        "<!-- @generated by python scripts/generate_cli_reference.py --write -->",
        "# CLI Reference",
        "",
        "This reference is generated from the argparse definitions used by Gearu.",
        "Do not edit the mechanical help text directly; update the CLI and regenerate it.",
        "",
        "```sh",
        "python scripts/generate_cli_reference.py --write",
        "python scripts/generate_cli_reference.py --check",
        "```",
        "",
    ]
    for title, help_text in sections:
        output.extend(
            [
                f"## `{title}`",
                "",
                "```text",
                help_text.rstrip(),
                "```",
                "",
            ]
        )
    return "\n".join(output)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate or check Gearu's CLI reference."
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--write",
        action="store_true",
        help="rewrite docs/CLI.md from the current CLI definitions",
    )
    mode.add_argument(
        "--check",
        action="store_true",
        help="fail if docs/CLI.md is not current",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    generated = generated_markdown()
    if args.write:
        DOCS_PATH.write_text(generated, encoding="utf-8", newline="\n")
        print(f"wrote {DOCS_PATH}", file=sys.stderr)
        return 0
    if args.check:
        try:
            current = DOCS_PATH.read_text(encoding="utf-8")
        except FileNotFoundError:
            current = ""
        if current != generated:
            print(
                f"{DOCS_PATH} is out of date; regenerate with: "
                "python scripts/generate_cli_reference.py --write",
                file=sys.stderr,
            )
            return 1
        return 0
    print(generated, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
